// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLRiaS3jvOZ2NlzvOi4bIAjuXo4qV5PYk',
    appId: '1:66235768002:web:cc8f245aedb38fdd056f5b',
    messagingSenderId: '66235768002',
    projectId: 'svinobook',
    authDomain: 'svinobook.firebaseapp.com',
    storageBucket: 'svinobook.firebasestorage.app',
    measurementId: 'G-T5CZ9WX6GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT4NT0bOe6L-dqSSCSlX3G8CkxettLkws',
    appId: '1:66235768002:android:4ec798cc55ec9725056f5b',
    messagingSenderId: '66235768002',
    projectId: 'svinobook',
    storageBucket: 'svinobook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlueakvXA4_xTWYnb-MbTIdmcR98Py-Wk',
    appId: '1:66235768002:ios:77c19965e83f1bc8056f5b',
    messagingSenderId: '66235768002',
    projectId: 'svinobook',
    storageBucket: 'svinobook.firebasestorage.app',
    iosBundleId: 'com.example.svinobook',
  );
}
